### ISSUE TITLE
Targeted Payment Model

### ISSUE THREAD

**Issue by chris-brown-nz** [chris-brown-nz/stockmarketbi#43]

**Comment by chris-brown-nz** [comment]
======================================================================
ERROR: test_init (stockmarketbi.test.test_model.TestTargetedPayment_Model)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\apps\stockmarketbi\stockmarketbi\test\test_model.py", line 16, in test_init
    mdl = targeted_payment.Model()
TypeError: __init__() missing 3 required positional arguments: 'start_date', 'end_date', and 'max_monthly_payments'

**Comment by chris-brown-nz** [comment]
```
======================================================================
ERROR: test_init (stockmarketbi.test.test_model.TestTargetedPayment_Model)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\apps\stockmarketbi\stockmarketbi\test\test_model.py", line 21, in test_init
    mdl = targeted_payment.Model()
TypeError: __init__() missing 3 required positional arguments: 'start_date', 'end_date', and 'max_monthly_payments'

======================================================================
ERROR: test_read_xlsx (stockmarketbi.test.test_model.TestTargetedPayment_Model)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\apps\stockmarketbi\stockmarketbi\test\test_model.py", line 25, in test_read_xlsx
    mdl = targeted_payment.load_xlsx()
AttributeError: module 'stockmarketbi.model.targeted_payment' has no attribute 'load_xlsx'

----------------------------------------------------------------------
```

**Comment by chris-brown-nz** [comment]
```
======================================================================
ERROR: test_init (stockmarketbi.test.test_model.TestTargetedPayment_Model)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\apps\stockmarketbi\stockmarketbi\test\test_model.py", line 20, in test_init
    mdl = targeted_payment.Model()
TypeError: __init__() missing 3 required positional arguments: 'start_date', 'end_date', and 'max_monthly_payments'

======================================================================
FAIL: test_read_xlsx (stockmarketbi.test.test_model.TestTargetedPayment_Model)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\apps\stockmarketbi\stockmarketbi\test\test_model.py", line 24, in test_read_xlsx
    self.assertTrue(False)
AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by chris-brown-nz** [comment]
Working on Model.read_xlsx()

**Comment by chris-brown-nz** [comment]
Todo:

- summary
- balances
- manual testing
- build unit test to compare results of complex.json to stored dfs
- don't think fees are taken into account for allocation of spare funds
- avoid using returns all over the place in Model.calculate()

**Comment by chris-brown-nz** [comment]
Todo:

- include sheet on output spreadsheet showing model attributes and app version
- new sheet on output spreadsheet - list of accounts
- don't think fees are taken into account for allocation of spare funds
- avoid using returns all over the place in Model.calculate()

**Comment by chris-brown-nz** [comment]
Todo:

- add option for minimum balance on all accounts (voluntary payment will have priority for these account)
- new sheet on output spreadsheet - list of accounts
- don't think fees are taken into account for allocation of spare funds
- avoid using returns all over the place in Model.calculate()

**Comment by chris-brown-nz** [comment]
Todo:

add date that account was closed
add option for minimum balance on all accounts (voluntary payment will have priority for these account)
new sheet on output spreadsheet - list of accounts
don't think fees are taken into account for allocation of spare funds
avoid using returns all over the place in Model.calculate()

**Comment by chris-brown-nz** [comment]
Todo:

- rename principal to starting_balance
- add option for minimum balance on all accounts (voluntary payment will have priority for these account)
- don't think fees are taken into account for allocation of spare funds
- surplus funds are being left in closed accounts instead of being used for voluntary payments

**Comment by chris-brown-nz** [comment]
Just need to add CLI option

**Comment by chris-brown-nz** [comment]
```
(stockmarketbi) C:\apps\stockmarketbi>python smbi.py --debug=true model targeted-payment --start-date=2019-12-22 --end-date=2019-12-22 --max-monthly-payments=10000.29 --input-file=testin.xlsx --output-file=testout.xlsx --use-default-path=true
2019-12-23Z09:00:56  20  SMBI    App() instance created
2019-12-23Z09:00:56  10  SMBI    CLI Args: Namespace(debug='true', end_date='2019-12-22', input_file='testin.xlsx', max_monthly_payments='10000.29', model_subparser='targeted-payment', output_file='testout.xlsx', start_date='2019-12-22', subparser='model', use_default_path='true')
```

**Comment by chris-brown-nz** [comment]
Done
