### ISSUE TITLE
Need to create data directories automatically

### ISSUE THREAD

**Issue by chris-brown-nz** [chris-brown-nz/stockmarketbi#51]
```
(test) chris@test:~$ python -m stockmarketbi.smbi
2019-12-27Z23:00:18  20  SMBI    App() instance created
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chris/virtual_environments/test/lib/python3.8/site-packages/stockmarketbi/smbi.py", line 4, in <module>
    app = App(sender='SMBI')
  File "/home/chris/virtual_environments/test/lib/python3.8/site-packages/stockmarketbi/app.py", line 84, in __init__
    log.write(self, 'App() instance created', level=log.INFO)
  File "/home/chris/virtual_environments/test/lib/python3.8/site-packages/stockmarketbi/core/log.py", line 44, in write
    with open(logfile, 'a') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '~/smbi-data/log/20191227Z_finance.log'
```

**Comment by chris-brown-nz** [comment]
done, tested
