### ISSUE TITLE
create etl pipeline

### ISSUE THREAD

**Issue by chris-brown-nz** [chris-brown-nz/stockmarketbi#73]

**Comment by chris-brown-nz** [comment]
look at using multi-threading for etl: https://realpython.com/intro-to-python-threading/

could have one (main?) thread tracking performance

track time taken for different etl stages

**Comment by chris-brown-nz** [comment]
```
(stockmarketbi) C:\apps\stockmarketbi>python -m stockmarketbi.etl.pipeline
2020-01-20Z02:59:17+00:00  20  SMBI    App() instance created
2020-01-20Z02:59:17+00:00  20  SMBI    ETL (extract) start: etl_dbinfo / dbinfo
2020-01-20Z02:59:18+00:00  20  SMBI    ETL (extract) stop: etl_dbinfo / dbinfo
2020-01-20Z02:59:18+00:00  20  SMBI    ETL (transform) start: etl_dbinfo / smbi_dim_database_table
2020-01-20Z02:59:18+00:00  20  SMBI    ETL (transform) stop: etl_dbinfo / smbi_dim_database_table
2020-01-20Z02:59:18+00:00  20  SMBI    ETL (load) start: etl_dbinfo / smbi_dim_database_table
2020-01-20Z02:59:18+00:00  20  SMBI    ETL (load) stop: etl_dbinfo / smbi_dim_database_table
2020-01-20Z02:59:18+00:00  20  SMBI    ETL (transform) start: etl_dbinfo / smbi_fact_database
2020-01-20Z02:59:18+00:00  20  SMBI    ETL (transform) stop: etl_dbinfo / smbi_fact_database
2020-01-20Z02:59:18+00:00  20  SMBI    ETL (load) start: etl_dbinfo / smbi_fact_database
2020-01-20Z02:59:18+00:00  20  SMBI    ETL (load) stop: etl_dbinfo / smbi_fact_database

(stockmarketbi) C:\apps\stockmarketbi>python -m stockmarketbi.etl.pipeline
2020-01-20Z02:59:37+00:00  20  SMBI    App() instance created
Traceback (most recent call last):
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\session.py", line 2577, in _flush
    flush_context.execute()
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\persistence.py", line 205, in save_obj
    for (
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\persistence.py", line 373, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\persistence.py", line 1604, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\session.py", line 311, in connection
    self._assert_active()
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\session.py", line 304, in _assert_active
    raise sa_exc.ResourceClosedError(closed_msg)
sqlalchemy.exc.ResourceClosedError: This transaction is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\apps\stockmarketbi\stockmarketbi\etl\pipeline.py", line 168, in <module>
    p.run()
  File "C:\apps\stockmarketbi\stockmarketbi\etl\pipeline.py", line 55, in run
    result = meta['result'].result()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\apps\stockmarketbi\stockmarketbi\etl\pipeline.py", line 62, in etl_dbinfo
    self.log_target(thread, 'e', 'dbinfo', 'start')
  File "C:\apps\stockmarketbi\stockmarketbi\etl\pipeline.py", line 157, in log_target
    self.app.session.commit()
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\session.py", line 1036, in commit
    self.transaction.commit()
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\session.py", line 503, in commit
    self._prepare_impl()
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\session.py", line 482, in _prepare_impl
    self.session.flush()
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\session.py", line 2479, in flush
    self._flush(objects)
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\util\langhelpers.py", line 79, in __exit__
    compat.reraise(type_, value, traceback)
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\session.py", line 519, in rollback
    self._assert_active(prepared_ok=True, rollback_ok=True)
  File "C:\apps_venv\stockmarketbi\lib\site-packages\sqlalchemy\orm\session.py", line 304, in _assert_active
    raise sa_exc.ResourceClosedError(closed_msg)
sqlalchemy.exc.ResourceClosedError: This transaction is closed

(stockmarketbi) C:\apps\stockmarketbi>
```

**Comment by chris-brown-nz** [comment]
Took session out of App() object and changed references to app.session
